# Pentagon numbers
# Problem 44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
# is minimised; what is the value of D?

from math import sqrt


def is_pentagonal(num):
    return ((1 + sqrt(1 + 24 * num)) / 6).is_integer()


def gen_pent_num(num):
    return num * (3 * num - 1) // 2


pent_nums = [1]
pent_index = 2
D = 0
while not D:
    new_pent = gen_pent_num(pent_index)
    for x in pent_nums:
        sub_value = new_pent - x
        add_value = new_pent + x
        if sub_value in pent_nums:
            if is_pentagonal(add_value):
                D = sub_value
                break
    pent_nums.append(new_pent)
    pent_index += 1
print(D)
