# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

fibolist = [1, 2]
max_value = 4 * 10 ** 6

current = sum(fibolist[-2:])
while current < max_value:
    fibolist.append(current)
    current = sum(fibolist[-2:])

print(sum([x for x in fibolist if not x % 2]))
